name: numpyro_example
channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - pip
  - python>=3.9
  - jupyterlab
  - numpyro
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupytext